[platformio]
default_envs = companion_tree

[env:companion_tree]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D USER_SETUP_LOADED=1
  -D ST7796_DRIVER=1
  -D TFT_WIDTH=320
  -D TFT_HEIGHT=480
  -D TFT_MOSI=11
  -D TFT_SCLK=12
  -D TFT_CS=10
  -D TFT_DC=9
  -D TFT_RST=14
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SPI_FREQUENCY=40000000
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  knolleary/PubSubClient@^2.8
  fastled/FastLED@^3.9.15
  bodmer/TFT_eSPI@^2.5.43
  claws/BH1750@^1.3.0
  adafruit/Adafruit SHT31 Library@^2.2.2
  adafruit/RTClib@^2.1.4
