// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTosxCjoRLcc-QUKPS02beUUlFK6dzQ4',
    appId: '1:73435559656:android:8cb7caf0b702d4070afb5d',
    messagingSenderId: '73435559656',
    projectId: 'elder-tree-esg-z1nnz',
    storageBucket: 'elder-tree-esg-z1nnz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrrHflPguaeXhHj8W66s5ptaA7XiTnP1Q',
    appId: '1:73435559656:ios:5d704cd2969018d50afb5d',
    messagingSenderId: '73435559656',
    projectId: 'elder-tree-esg-z1nnz',
    storageBucket: 'elder-tree-esg-z1nnz.firebasestorage.app',
    iosBundleId: 'com.eldertree.elderTreeMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrrHflPguaeXhHj8W66s5ptaA7XiTnP1Q',
    appId: '1:73435559656:ios:5d704cd2969018d50afb5d',
    messagingSenderId: '73435559656',
    projectId: 'elder-tree-esg-z1nnz',
    storageBucket: 'elder-tree-esg-z1nnz.firebasestorage.app',
    iosBundleId: 'com.eldertree.elderTreeMobile',
  );
}
